name: Deploy Validator Profile to Cloudflare R2

on:
  push:
    branches: [main]
    paths:
      - 'validator-profile/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      UPLOAD_PATH: ${{ secrets.UPLOAD_PATH_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rclone
        run: |
          curl -O https://downloads.rclone.org/rclone-current-linux-amd64.deb
          sudo dpkg -i rclone-current-linux-amd64.deb

      - name: Configure Rclone for Cloudflare R2
        run: |
          mkdir -p ~/.config/rclone/
          cat <<EOF > ~/.config/rclone/rclone.conf
          [cloudflare_r2]
          type = s3
          provider = Cloudflare
          access_key_id = ${{ secrets.CF_R2_ACCESS_KEY_ID }}
          secret_access_key = ${{ secrets.CF_R2_SECRET_ACCESS_KEY }}
          endpoint = ${{ secrets.CF_R2_ENDPOINT }}
          EOF

      # (Optional) List bucket contents before sync
      - name: List bucket contents before sync
        run: |
          rclone ls "${{ env.UPLOAD_PATH }}" || echo "Bucket is empty or inaccessible"

      - name: Sync entire validator-profile folder to Cloudflare R2
        run: |
          rclone sync validator-profile "${{ env.UPLOAD_PATH }}" --progress

      # (Optional) List bucket contents after sync
      - name: List bucket contents after sync
        run: |
          rclone ls "${{ env.UPLOAD_PATH }}"
